$NetBSD$

--- rsvg_internals/Cargo.toml.orig	2018-10-09 13:52:22.000000000 +0000
+++ rsvg_internals/Cargo.toml
@@ -73,7 +73,7 @@ criterion = "0.2"
 
 [lib]
 name = "rsvg_internals"
-crate-type = ["staticlib", "lib"]
+crate-type = ["staticlib", "lib", "dylib"]
 
 [[bench]]
 name = "box_blur"
